version: '3.8'

services:
  note-summarizer:
    build: .
    container_name: note-summarizer
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - cache-volume:/app/.cache
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_THEME_BASE=light
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  cache-volume:
    name: note-summarizer-cache